### ISSUE TITLE
Failed to load the split-diff package

### ISSUE THREAD

**Issue by pistou** [taniarascia/new-moon-atom-syntax#10]
[Enter steps to reproduce:]

1. Install `new-moon-atom-syntax`
2. Use `new-moon-atom-syntax` as syntax theme

**Atom**: 1.17.0 ia32
**Electron**: 1.3.15
**OS**: Windows 10 (Creators update)
**Thrown From**: [split-diff](https://github.com/mupchrch/split-diff) package 1.4.0

### Stack Trace

Failed to load the split-diff package

```
At error evaluating function `fade`: color.toHSL is not a function in C:\Users\Pierre\.atom\packages\split-diff\styles\split-diff.less:12:24

LessError: error evaluating function `fade`: color.toHSL is not a function
  at /packages/split-diff/styles/split-diff.less:12:24
```

### Commands

```
     -0:24.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

**Comment by taniarascia** [comment]
Thanks, I don't know why that happened. I'll look into it.

**Comment by pistou** [comment]
FYI, the error comes from [split-diff.less](https://github.com/mupchrch/split-diff/blob/master/styles/split-diff.less#L12)
`background-color: fade(@syntax-color-removed, 40%);`

Is there something specific about `@syntax-color-removed` in your code?
