### ISSUE TITLE
Causes atom crash and cannot open atom.

### ISSUE THREAD

**Issue by Jahhein** [taniarascia/new-moon-atom-syntax#11]
Installing this package through atom's settings > install > themes caused atom to crash, and no longer be able to open/use.

when trying to re-open it prompts with a developer tools debug window.

For anyone else that encounters this problem, to solve it you'll need to manually delete the package from atom so you don't need to reinstall atom.

` rm -rfv ~/.atom/packages/new-moon-atom-syntax/ `

Opening atom after this will force atom to use a default syntax theme Atom Dark.

Hopefully someone may be able to fix the issue, however being short on time I couldn't find the reason behind this.

**Comment by taniarascia** [comment]
Hmm, I'm not sure why that happened. I'll try to replicate on the latest version of Atom and see what might be the issue.

**Comment by taniarascia** [comment]
I just reinstalled the latest Atom and New Moon with no issue. What OS are you using?

**Comment by Jahhein** [comment]
Specifications: 

- Macbook Pro Retina mid-2012 model 10,1
- Mac OS X 10.12.6

I did post this issue before the newest Atom 1.19.0 release, perhaps that was the release you used and it worked?

**Comment by taniarascia** [comment]
Hmm, I'm using a MBP Retina 2015 on the same OS, no problem. It probably had a conflict with another extension you were using. I should probably update the theme with the latest specifications, as I made it over a year ago and they seem to keep changing the way they do their themes.
