### ISSUE TITLE
I like it; but with invisible characters turned on it's too busy...

### ISSUE THREAD

**Issue by doughsay** [taniarascia/new-moon-atom-syntax#9]
See screenshot:

![screen shot 2017-03-12 at 11 16 24 am](https://cloud.githubusercontent.com/assets/221693/23834548/7adbfb1c-0715-11e7-9be5-c190813950a6.png)

In the default atom theme (and most themes), invisible characters are rendered in a color very close to the background color, so they don't distract.

**Comment by taniarascia** [comment]
Ah, I didn't notice because I didn't have invisible characters enabled. Thanks for pointing it out! I'll work on fixing it in a week or so. (Additionally, if you know how to fix it, I'll pull any patch!)
